_wandb:
    value:
        cli_version: 0.22.2
        e:
            cwcd55hgdfr9cdevi1upd0fv64n18cts:
                email: ruchidattab@gmail.com
                executable: /Users/ruchibommaraju/Northwestern/weavehacks2/.venv/bin/python
                git:
                    commit: 9777211ce2bf00837cb054a9b483d149bb39434a
                    remote: https://github.com/imruchi/weavehacks2.git
                host: Ruchis-MacBook-Pro.local
                os: macOS-15.5-arm64-arm-64bit
                program: <python with no main file>
                python: CPython 3.12.7
                root: /Users/ruchibommaraju/Northwestern/weavehacks2
                startedAt: "2025-10-12T14:50:53.323485Z"
                writerId: cwcd55hgdfr9cdevi1upd0fv64n18cts
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 105
            "2":
                - 105
            "4": 3.12.7
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
